services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/statistics
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  main-service:
    build: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
  main-db:
    image: postgres:16.1
